dist: bionic
language: python
cache:
  - pip
env:
  global:
  - AWS_REGION="us-east-1"

before_install:
  - pip install --upgrade pip 'attrs==19.2.0' -r requirements.txt

install:
  - pip install .

script:
  - pre-commit run --all-files
  - python setup.py sdist bdist_wheel
  - twine check ./dist/*

jobs:
  include:
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"
    - stage: Deploy
      script: skip
      python: 3.8
      deploy:
        provider: pypi
        user: aws-cloudformation-developers
        password:
          secure: ACHz2AGFnR0QWjwRzO3mpO0lnM/WTEQVtY0p8cbf3CrbwJW/DzqAD/IwFWC4dK0CND2VObYuQb0n8mLQKw5k9Bx464NThOu4CEZhRj7oUvMLXAgTAMOsi8GDMMRv7iyBeEvOs5D2cSeLtZEL2sPd3hXcsEG6Mb03DWG66CM3K1/MHmsnKI1dlqgvzzJb2i6dmM2ZAxW90/fAW9Qc4qLLLg93K3vvWm4y+XdOBukf554vPZxRAcEJ4ywjf/e3J1oGDDqs1uWgO4klrZJOjnxaeM+cL1IRCldq1ITQgyczoqBH8eM6QaT0cccs8GiM4z+Le15rwvahm2JV418XbsGrmL39gabLwZarKaVXwlEmLq0LVs0uXoi4RzYfQTULh0vlUprm/4+zhKLEg2YC1fy0dz2V7FB4n2RrC7T72sjbjXtWgTCfw/V+G6DJ2omvTSUsD9oG6L9L0FZ3f0sQV4uvQJ0tzyij+EsbZJ6FFPe71VPCXvTUsFHLN3xRkTSSR2OJg7gO6MmUhvWjewUo+QX9LY6EszU5POZ4Yg4jfeftpJDXUN/dX2pUSr6NuWNvYjf9J5OYvfTtOV6eD4a+2GWLRs7F1pKXVo5K4VCFhIe3qwZh4IF8S5nFUyUVq7WG/CLAh0d6oRIuetKMTzNNrTh1j4vpEVbVofOTDi7BmkIICCo=
        on:
          tags: true
        distributions: sdist bdist_wheel
        skip_existing: true
